### ISSUE TITLE
Crashing in Sentry 8.22.0

### ISSUE THREAD

**Issue by Kiina** [NDrive/sentry-mattermost#6]
It isnt showing up in my list after installing so I looked at the logs:

```
Failed to load plugin 'mattermost':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/sentry_mattermost/plugin.py", line 29, in <module>
    from sentry.models import TagKey, TagValue
ImportError: cannot import name TagKey
```

Looks like there a few changes which prevent the plugin from loading on the current sentry version.

**Comment by jaltek** [comment]
As @Kiina already suggested a fix would you please accept it?
Works for me in 8.22.0.

**Comment by robdewit** [comment]
Please merge this commit.

**Comment by andreaspapadakis** [comment]
This issue is still open for me, using Sentry 9.1.2:

```
Failed to load plugin 'mattermost':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 32, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/sentry_mattermost/plugin.py", line 29, in <module>
    from sentry.models import TagKey, TagValue
ImportError: cannot import name TagKey
```

Snapshot of the python packages:

```
sentry==9.1.2
sentry-mattermost==0.0.1
sentry-plugins==9.1.2
sentry-sdk==0.13.0
````

**Comment by Kiina** [comment]
You need to install from git as the pip release isn't updated
